spring.application.name=smartbudget

server.port=8081

# ===============================
# Banco de dados H2
# ===============================
spring.datasource.url=jdbc:h2:mem:smartbudget
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=true

spring.h2.console.enabled=true


# ===============================
# Spring AI + Ollama LOCAL
# ===============================
spring.ai.ollama.base-url=http://localhost:11434

spring.ai.model.chat=ollama

spring.ai.ollama.chat.model=llama3.2

spring.ai.ollama.chat.temperature=0.2